### PR TITLE
If entity id is 0 editor.controller.js treats it as "isnew"

### PR DESCRIPTION
**Pull request by tobbbe**
in javascript 0 == "0" is true 😂

### CODE REVIEW

**Comment by mattbrailsford** [comment]
Hmm, but that would suggest you could have an entity ID with a value of 0 which isn't allowed. 🤔

**Comment by tobbbe** [comment]
oh! :O didnt know that. Is that in the docs somewhere?

**Comment by mattbrailsford** [comment]
@tobbbe not in the docs I don't think, but it pretty much assumes an ID is an int and so '0' being the default value for an int, that's how we determine something is new.

**Comment by tobbbe** [comment]
okey, makes sense!

**Pull request closed without merging**
